### PR TITLE
DAOS-4983 build: Update MACSio build to SLES15.2

### PR DESCRIPTION
**Pull request by phender**
Update MACSio spec file and packaging files to support SLES15.2.

PR-repos: hdf5@PR-14

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by phender** [comment]
Verifying change in https://github.com/daos-stack/daos/pull/3243

**Review by brianjmurrell — APPROVED** [review]

**Comment by phender** [comment]
Verified provided RPM is now correct:
```
[pahender@wolf-10 ftest]$ rpm -qp --provides ~/rpm/MACSio-openmpi3-1.1-3.el7.x86_64_1.rpm
MACSio-openmpi3 = 1.1-3.el7
MACSio-openmpi3(x86-64) = 1.1-3.el7
MACSio-openmpi3-daos-0 = 1.1-3.el7
```

Previously the unassigned variable was being used verbatim:
```
[pahender@wolf-10 ftest]$ rpm -qp --provides ~/rpm/MACSio-openmpi3-1.1-3.el7.x86_64.rpm
MACSio-openmpi3 = 1.1-3.el7
MACSio-openmpi3(x86-64) = 1.1-3.el7
MACSio-openmpi3-daos-%{daos_major} = 1.1-3.el7
```

**Review by brianjmurrell — APPROVED** [review]

**Comment by phender** [comment]
The openmpi3 MACSio tests passed in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3243/22/artifact/Functional/job-2020-08-26T16.23-56455f3-io-macsio_test/ using the RPMs from this PR.

**Review by mjean308 — APPROVED** [review]
looks good to me

**Pull request merged**
