### PR TITLE
CORCI-991 build: Update MACSio with latest HDF5

### PR DESCRIPTION
**Pull request by mjean308**
PR-repos: hdf5@PR-16

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### CODE REVIEW

**Comment by mjean308** [comment]
PR-3812 is currently in progress to test ior-hpc; hdf5-vol-daos and hdf5 in daos CI

**Review by phender — COMMENTED** [review]
Shouldn't the rpm spec file version be updated in the spec file if this is providing different code?

**Comment by brianjmurrell** [comment]
@mjean308 Why does this need to be rebuilt?  Did the major version of the hdf5 library change?

**Comment by mjean308** [comment]
the hdf5 libhdf5.so was updated from libhdf5.so.200 to libhdf5.so.1000 so macsio rpms would not install when running the DAOS RP

**Comment by brianjmurrell** [comment]
> the hdf5 libhdf5.so was updated from libhdf5.so.200 to libhdf5.so.1000 so macsio rpms would not install when running the DAOS RP

I commented elsewhere that that kind of jump seems very suspicious.  We should understand why it jumped so much and make sure it's not a problem of our build/packaging.  That would mean finding the commit that jumped it most recently.  Can you please locate that?

**Review by phender — APPROVED** [review]

**Review by brianjmurrell — APPROVED** [review]

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
